[features]
seeds = false
skip-lint = false
[programs.devnet]
news = "3hJc8UD8dCKpuJiBzKwfeAmxBS2AmCCbUczKRL7x3QGV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/gitpod/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
